/*
 * SPDX-FileCopyrightText: Copyright (c) 1993-2004 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */


#ifndef clceb6_h_
#define clceb6_h_

#include "nvtypes.h"

#ifdef __cplusplus
extern "C" {
#endif

#define NVCEB6_VIDEO_COMPOSITOR                                             (0x0000CEB6U)

#define NVCEB6_VIDEO_COMPOSITOR_NOP                                                              (0x00000100U)
#define NVCEB6_VIDEO_COMPOSITOR_NOP_PARAMETER                                                    31:0
#define NVCEB6_VIDEO_COMPOSITOR_NOP_PARAMETER_HIGH_FIELD                                         31U
#define NVCEB6_VIDEO_COMPOSITOR_NOP_PARAMETER_LOW_FIELD                                          0U
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER                                                       (0x00000140U)
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_V                                                     31:0
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_V_HIGH_FIELD                                          31U
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_V_LOW_FIELD                                           0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID                                               (0x00000200U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID                                            31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_HIGH_FIELD                                 31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_LOW_FIELD                                  0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_MPEG12                                     (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_VC1                                        (0x00000002U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_H264                                       (0x00000003U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_MPEG4                                      (0x00000004U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_VP8                                        (0x00000005U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_CTR64                                      (0x00000006U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_HEVC                                       (0x00000007U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_NEW_H264                                   (0x00000008U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_VP9                                        (0x00000009U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_PASS1                                      (0x0000000AU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_HEVC_PARSER                                (0x0000000CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_UCODE_TEST                                 (0x0000000DU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_HWDRM_PR_DECRYPTAUDIO                      (0x0000000EU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_HWDRM_PR_DECRYPTAUDIOMULTIPLE              (0x0000000FU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_HWDRM_PR_PREPROCESSENCRYPTEDDATA           (0x00000010U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_VP9_PARSER                                 (0x00000011U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_APPLICATION_ID_ID_AVD                                        (0x00000012U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_WATCHDOG_TIMER                                               (0x00000204U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_WATCHDOG_TIMER_TIMER                                         31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_WATCHDOG_TIMER_TIMER_HIGH_FIELD                              31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_WATCHDOG_TIMER_TIMER_LOW_FIELD                               0U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_A                                                      (0x00000240U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_A_UPPER                                                7:0
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_A_UPPER_HIGH_FIELD                                     7U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_A_UPPER_LOW_FIELD                                      0U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_B                                                      (0x00000244U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_B_LOWER                                                31:0
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_B_LOWER_HIGH_FIELD                                     31U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_B_LOWER_LOW_FIELD                                      0U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_C                                                      (0x00000248U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_C_PAYLOAD                                              31:0
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_C_PAYLOAD_HIGH_FIELD                                   31U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_C_PAYLOAD_LOW_FIELD                                    0U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SAVE_AREA                                                    (0x0000024CU)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SAVE_AREA_OFFSET                                             31:0
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SAVE_AREA_OFFSET_HIGH_FIELD                                  31U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SAVE_AREA_OFFSET_LOW_FIELD                                   0U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH                                                       (0x00000250U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP                                                    1:0
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP_HIGH_FIELD                                         1U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP_LOW_FIELD                                          0U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP_CTX_UPDATE                                         (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP_CTX_SAVE                                           (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP_CTX_RESTORE                                        (0x00000002U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_OP_CTX_FORCERESTORE                                   (0x00000003U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTXID_VALID                                           2:2
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTXID_VALID_HIGH_FIELD                                2U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTXID_VALID_LOW_FIELD                                 2U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTXID_VALID_FALSE                                     (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTXID_VALID_TRUE                                      (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_RESERVED0                                             7:3
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_RESERVED0_HIGH_FIELD                                  7U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_RESERVED0_LOW_FIELD                                   3U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTX_ID                                                23:8
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTX_ID_HIGH_FIELD                                     23U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_CTX_ID_LOW_FIELD                                      8U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_RESERVED1                                             31:24
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_RESERVED1_HIGH_FIELD                                  31U
#define NVCEB6_VIDEO_COMPOSITOR_CTX_SWITCH_RESERVED1_LOW_FIELD                                   24U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_LOWER                                      (0x00000254U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_LOWER_PAYLOAD_LOWER                        31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_LOWER_PAYLOAD_LOWER_HIGH_FIELD             31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_LOWER_PAYLOAD_LOWER_LOW_FIELD              0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_UPPER                                      (0x00000258U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_UPPER_PAYLOAD_UPPER                        31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_UPPER_PAYLOAD_UPPER_HIGH_FIELD             31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SEMAPHORE_PAYLOAD_UPPER_PAYLOAD_UPPER_LOW_FIELD              0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_A                        (0x0000025CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_A_LOWER                  31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_A_LOWER_HIGH_FIELD       31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_A_LOWER_LOW_FIELD        0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_B                        (0x00000260U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_B_UPPER                  31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_B_UPPER_HIGH_FIELD       31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_MONITORED_FENCE_SIGNAL_ADDRESS_BASE_B_UPPER_LOW_FIELD        0U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE                                                          (0x00000300U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY                                                   0:0
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_HIGH_FIELD                                        0U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_LOW_FIELD                                         0U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_DISABLE                                           (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_ENABLE                                            (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_ON                                                1:1
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_ON_HIGH_FIELD                                     1U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_ON_LOW_FIELD                                      1U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_ON_END                                            (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_NOTIFY_ON_BEGIN                                          (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION                                              2:2
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_HIGH_FIELD                                   2U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_LOW_FIELD                                    2U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_DISABLE                                      (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_ENABLE                                       (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_OP                                           3:3
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_OP_HIGH_FIELD                                3U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_OP_LOW_FIELD                                 3U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_OP_EQUAL_ZERO                                (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_PREDICATION_OP_NOT_EQUAL_ZERO                            (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_AWAKEN                                                   8:8
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_AWAKEN_HIGH_FIELD                                        8U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_AWAKEN_LOW_FIELD                                         8U
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_AWAKEN_DISABLE                                           (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_EXECUTE_AWAKEN_ENABLE                                            (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D                                                      (0x00000304U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_STRUCTURE_SIZE                                       1:0
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_STRUCTURE_SIZE_HIGH_FIELD                            1U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_STRUCTURE_SIZE_LOW_FIELD                             0U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_STRUCTURE_SIZE_ONE                                   (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_STRUCTURE_SIZE_FOUR                                  (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_STRUCTURE_SIZE_TWO                                   (0x00000002U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_AWAKEN_ENABLE                                        8:8
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_AWAKEN_ENABLE_HIGH_FIELD                             8U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_AWAKEN_ENABLE_LOW_FIELD                              8U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_AWAKEN_ENABLE_FALSE                                  (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_AWAKEN_ENABLE_TRUE                                   (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION                                            17:16
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION_HIGH_FIELD                                 17U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION_LOW_FIELD                                  16U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION_RELEASE                                    (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION_RESERVED_0                                 (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION_RESERVED_1                                 (0x00000002U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_OPERATION_TRAP                                       (0x00000003U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_FLUSH_DISABLE                                        21:21
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_FLUSH_DISABLE_HIGH_FIELD                             21U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_FLUSH_DISABLE_LOW_FIELD                              21U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_FLUSH_DISABLE_FALSE                                  (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_FLUSH_DISABLE_TRUE                                   (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_TRAP_TYPE                                            23:22
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_TRAP_TYPE_HIGH_FIELD                                 23U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_TRAP_TYPE_LOW_FIELD                                  22U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_TRAP_TYPE_UNCONDITIONAL                              (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_TRAP_TYPE_CONDITIONAL                                (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_TRAP_TYPE_CONDITIONAL_EXT                            (0x00000002U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_PAYLOAD_SIZE                                         24:24
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_PAYLOAD_SIZE_HIGH_FIELD                              24U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_PAYLOAD_SIZE_LOW_FIELD                               24U
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_PAYLOAD_SIZE_32BIT                                   (0x00000000U)
#define NVCEB6_VIDEO_COMPOSITOR_SEMAPHORE_D_PAYLOAD_SIZE_64BIT                                   (0x00000001U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_AUXILIARY_DATA_BUFFER                                        (0x00000310U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_AUXILIARY_DATA_BUFFER_OFFSET                                 31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_AUXILIARY_DATA_BUFFER_OFFSET_HIGH_FIELD                      31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_AUXILIARY_DATA_BUFFER_OFFSET_LOW_FIELD                       0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_OFFSET                                 (0x00000314U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_OFFSET_OFFSET                          31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_OFFSET_OFFSET_HIGH_FIELD               31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_OFFSET_OFFSET_LOW_FIELD                0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_OFFSET                                (0x00000318U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_OFFSET_OFFSET                         31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_OFFSET_OFFSET_HIGH_FIELD              31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_OFFSET_OFFSET_LOW_FIELD               0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_MSB_OFFSET                             (0x0000031CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_MSB_OFFSET_OFFSET                      31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_MSB_OFFSET_OFFSET_HIGH_FIELD           31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_INPUT_MSB_OFFSET_OFFSET_LOW_FIELD            0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_MSB_OFFSET                            (0x00000320U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_MSB_OFFSET_OFFSET                     31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_MSB_OFFSET_OFFSET_HIGH_FIELD          31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_NOTIFIER_OUTPUT_MSB_OFFSET_OFFSET_LOW_FIELD           0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SUB_STREAM_ID                                                (0x00000324U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_SUB_STREAM_ID_OFFSET                                         31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SUB_STREAM_ID_OFFSET_HIGH_FIELD                              31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SUB_STREAM_ID_OFFSET_LOW_FIELD                               0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_JOB_DESCRIPTOR_BUF                                           (0x00000328U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_JOB_DESCRIPTOR_BUF_OFFSET                                    31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_JOB_DESCRIPTOR_BUF_OFFSET_HIGH_FIELD                         31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_JOB_DESCRIPTOR_BUF_OFFSET_LOW_FIELD                          0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS                                               (0x00000704U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_GPTIMER_ON                                    0:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_GPTIMER_ON_HIGH_FIELD                         0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_GPTIMER_ON_LOW_FIELD                          0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_DEBUG_MODE                                    1:1
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_DEBUG_MODE_HIGH_FIELD                         1U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_DEBUG_MODE_LOW_FIELD                          1U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_SCDEBUG_MODE                                  2:2
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_SCDEBUG_MODE_HIGH_FIELD                       2U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_SCDEBUG_MODE_LOW_FIELD                        2U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_FRAME_DONE_SOFT_RESET_EN                      3:3
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_FRAME_DONE_SOFT_RESET_EN_HIGH_FIELD           3U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_FRAME_DONE_SOFT_RESET_EN_LOW_FIELD            3U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_IGNORE_SOME_FIELDS_CHECK                      4:4
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_IGNORE_SOME_FIELDS_CHECK_HIGH_FIELD           4U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_IGNORE_SOME_FIELDS_CHECK_LOW_FIELD            4U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_MEM_WR_DISABLE                                5:5
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_MEM_WR_DISABLE_HIGH_FIELD                     5U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONTROL_PARAMS_MEM_WR_DISABLE_LOW_FIELD                      5U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONFIG_STRUCT_OFFSET                                         (0x00000708U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONFIG_STRUCT_OFFSET_OFFSET                                  31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONFIG_STRUCT_OFFSET_OFFSET_HIGH_FIELD                       31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_CONFIG_STRUCT_OFFSET_OFFSET_LOW_FIELD                        0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_FILTER_STRUCT_OFFSET                                         (0x0000070CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_FILTER_STRUCT_OFFSET_OFFSET                                  31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_FILTER_STRUCT_OFFSET_OFFSET_HIGH_FIELD                       31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_FILTER_STRUCT_OFFSET_OFFSET_LOW_FIELD                        0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_MISC_CONFIG_OFFSET                                           (0x00000710U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_MISC_CONFIG_OFFSET_OFFSET                                    31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_MISC_CONFIG_OFFSET_OFFSET_HIGH_FIELD                         31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_MISC_CONFIG_OFFSET_OFFSET_LOW_FIELD                          0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_LUMA_OFFSET                                   (0x00000720U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET                            31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET_HIGH_FIELD                 31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET_LOW_FIELD                  0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_U_OFFSET                               (0x00000724U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_U_OFFSET_OFFSET                        31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_U_OFFSET_OFFSET_HIGH_FIELD             31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_U_OFFSET_OFFSET_LOW_FIELD              0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_V_OFFSET                               (0x00000728U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_V_OFFSET_OFFSET                        31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_V_OFFSET_OFFSET_HIGH_FIELD             31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OUTPUT_SURFACE_CHROMA_V_OFFSET_OFFSET_LOW_FIELD              0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SFC_CRC_STRUCT_OFFSET                                        (0x00000730U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_SFC_CRC_STRUCT_OFFSET_OFFSET                                 31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SFC_CRC_STRUCT_OFFSET_OFFSET_HIGH_FIELD                      31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SFC_CRC_STRUCT_OFFSET_OFFSET_LOW_FIELD                       0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_INTF_CRC_STRUCT_OFFSET                                       (0x00000734U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_INTF_CRC_STRUCT_OFFSET_OFFSET                                31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_INTF_CRC_STRUCT_OFFSET_OFFSET_HIGH_FIELD                     31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_INTF_CRC_STRUCT_OFFSET_OFFSET_LOW_FIELD                      0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_OFFSET                                                (0x00000738U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_OFFSET_OFFSET                                         31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_OFFSET_OFFSET_HIGH_FIELD                              31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_STATUS_OFFSET_OFFSET_LOW_FIELD                               0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_EOTF_LUT_STRUCT_OFFSET                                       (0x00000740U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_EOTF_LUT_STRUCT_OFFSET_OFFSET                                31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_EOTF_LUT_STRUCT_OFFSET_OFFSET_HIGH_FIELD                     31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_EOTF_LUT_STRUCT_OFFSET_OFFSET_LOW_FIELD                      0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OETF_LUT_STRUCT_OFFSET                                       (0x00000744U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_OETF_LUT_STRUCT_OFFSET_OFFSET                                31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_OETF_LUT_STRUCT_OFFSET_OFFSET_HIGH_FIELD                     31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_OETF_LUT_STRUCT_OFFSET_OFFSET_LOW_FIELD                      0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TONE_MAP_LUT_STRUCT_OFFSET                                   (0x00000748U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TONE_MAP_LUT_STRUCT_OFFSET_OFFSET                            31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TONE_MAP_LUT_STRUCT_OFFSET_OFFSET_HIGH_FIELD                 31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TONE_MAP_LUT_STRUCT_OFFSET_OFFSET_LOW_FIELD                  0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_SURFACE_OFFSET                                        (0x0000074CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_SURFACE_OFFSET_OFFSET                                 31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_SURFACE_OFFSET_OFFSET_HIGH_FIELD                      31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_SURFACE_OFFSET_OFFSET_LOW_FIELD                       0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_DS_SURFACE_OFFSET                                     (0x00000750U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_DS_SURFACE_OFFSET_OFFSET                              31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_DS_SURFACE_OFFSET_OFFSET_HIGH_FIELD                   31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_DS_SURFACE_OFFSET_OFFSET_LOW_FIELD                    0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_NEIGHBOR_BUFFER_OFFSET                                (0x00000754U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_NEIGHBOR_BUFFER_OFFSET_OFFSET                         31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_NEIGHBOR_BUFFER_OFFSET_OFFSET_HIGH_FIELD              31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_XSOBEL_NEIGHBOR_BUFFER_OFFSET_OFFSET_LOW_FIELD               0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_LUMA_OFFSET                               (0x00000760U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET                        31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET_HIGH_FIELD             31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET_LOW_FIELD              0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_UOFFSET                            (0x00000764U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_UOFFSET_OFFSET                     31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_UOFFSET_OFFSET_HIGH_FIELD          31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_UOFFSET_OFFSET_LOW_FIELD           0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_VOFFSET                            (0x00000768U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_VOFFSET_OFFSET                     31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_VOFFSET_OFFSET_HIGH_FIELD          31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_OUTPUT_SURFACE_CHROMA_VOFFSET_OFFSET_LOW_FIELD           0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_LUMA_OFFSET                          (0x0000076CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET                   31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET_HIGH_FIELD        31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_LUMA_OFFSET_OFFSET_LOW_FIELD         0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_UOFFSET                       (0x00000770U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_UOFFSET_OFFSET                31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_UOFFSET_OFFSET_HIGH_FIELD     31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_UOFFSET_OFFSET_LOW_FIELD      0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_VOFFSET                       (0x00000774U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_VOFFSET_OFFSET                31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_VOFFSET_OFFSET_HIGH_FIELD     31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_PREV_OUTPUT_SURFACE_CHROMA_VOFFSET_OFFSET_LOW_FIELD      0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_OUTPUT_SURFACE_OFFSET                              (0x00000778U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_OUTPUT_SURFACE_OFFSET_OFFSET                       31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_OUTPUT_SURFACE_OFFSET_OFFSET_HIGH_FIELD            31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_OUTPUT_SURFACE_OFFSET_OFFSET_LOW_FIELD             0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_PREV_OUTPUT_SURFACE_OFFSET                         (0x0000077CU)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_PREV_OUTPUT_SURFACE_OFFSET_OFFSET                  31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_PREV_OUTPUT_SURFACE_OFFSET_OFFSET_HIGH_FIELD       31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_ALPHA_PREV_OUTPUT_SURFACE_OFFSET_OFFSET_LOW_FIELD        0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_NEIGHBOR_BUFFER_SURFACE_OFFSET                           (0x00000780U)
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_NEIGHBOR_BUFFER_SURFACE_OFFSET_OFFSET                    31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_NEIGHBOR_BUFFER_SURFACE_OFFSET_OFFSET_HIGH_FIELD         31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_TNR_NEIGHBOR_BUFFER_SURFACE_OFFSET_OFFSET_LOW_FIELD          0U
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_END                                                   (0x00001114U)
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_END_V                                                 31:0
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_END_V_HIGH_FIELD                                      31U
#define NVCEB6_VIDEO_COMPOSITOR_PM_TRIGGER_END_V_LOW_FIELD                                       0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_LUMA_OFFSET(b)                                  (0x00001200 + ((b)*0x00000004))
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_LUMA_OFFSET_OFFSET                              31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_LUMA_OFFSET_OFFSET_HIGH_FIELD                   31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_LUMA_OFFSET_OFFSET_LOW_FIELD                    0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_UOFFSET(b)                               (0x00001240 + ((b)*0x00000004))
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_UOFFSET_OFFSET                           31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_UOFFSET_OFFSET_HIGH_FIELD                31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_UOFFSET_OFFSET_LOW_FIELD                 0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_VOFFSET(b)                               (0x00001280 + ((b)*0x00000004))
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_VOFFSET_OFFSET                           31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_VOFFSET_OFFSET_HIGH_FIELD                31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SURFACE_CHROMA_VOFFSET_OFFSET_LOW_FIELD                 0U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SPARSE_WARP_MAP_OFFSET(b)                               (0x000012C0 + ((b)*0x00000004))
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SPARSE_WARP_MAP_OFFSET_OFFSET                           31:0
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SPARSE_WARP_MAP_OFFSET_OFFSET_HIGH_FIELD                31U
#define NVCEB6_VIDEO_COMPOSITOR_SET_SLOT_SPARSE_WARP_MAP_OFFSET_OFFSET_LOW_FIELD                 0U

#ifdef __cplusplus
};     /* extern "C" */
#endif
#endif // _clceb6_h

